# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\yueshenl\Desktop\PYMaterialInfoToJsonWsp\PDMSpider\MassageDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MassageDialog(object):
    def setupUi(self, MassageDialog):
        MassageDialog.setObjectName("MassageDialog")
        MassageDialog.resize(529, 346)
        self.gridLayout_2 = QtWidgets.QGridLayout(MassageDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(MassageDialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.TreeTable = QtWidgets.QWidget()
        self.TreeTable.setObjectName("TreeTable")
        self.MassageTree = QtWidgets.QTreeWidget(self.TreeTable)
        self.MassageTree.setGeometry(QtCore.QRect(10, 10, 511, 251))
        self.MassageTree.setObjectName("MassageTree")
        self.MassageTree.headerItem().setText(0, "1")
        self.tabWidget.addTab(self.TreeTable, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(MassageDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(MassageDialog)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(MassageDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MassageDialog)

    def retranslateUi(self, MassageDialog):
        _translate = QtCore.QCoreApplication.translate
        MassageDialog.setWindowTitle(_translate("MassageDialog", "爬取异常信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TreeTable), _translate("MassageDialog", "树形表格"))
        self.label.setText(_translate("MassageDialog", "生成报告"))
        self.pushButton.setText(_translate("MassageDialog", "保存"))
